import secrets
import string

# Gera uma senha forte com 20 caracteres import as libs e seja feliz
alphabet = string.ascii_letters + string.digits + string.punctuation
password = ''.join(secrets.choice(alphabet) for _ in range(20))
password

print(password)

# https://c340-187-101-169-197.ngrok-free.app
#Forwarding                    https://c340-187-101-169-197.ngrok-free.app -> http://localhost:4000                                                                                                                                              Connections                   ttl     opn     rt1     rt5     p50     p90                                                                             5       0       0.00    0.01    6.52    7.09                                                                                                                                                                      HTTP Requests                                                                                                           -------------                                                                                                                                                                                                                                   00:53:22.178 -12 GET /api/installations         304 Not Modified                                                        00:53:22.108 -12 GET /favicon.ico               304 Not Modified                                                        00:53:21.672 -12 GET /styles.css                304 Not Modified                                                        00:53:21.761 -12 GET /api/devices               304 Not Modified                                                        00:53:21.594 -12 GET /                          304 Not Modified                                                        00:53:21.675 -12 GET /script.js                 304 Not Modified                                                        00:52:44.680 -12 GET /api/devices               200 OK                                                                  00:52:44.761 -12 GET /favicon.ico               200 OK                                                                  00:52:44.821 -12 GET /api/installations         200 OK                                                                  00:52:43.775 -12 GET /                          200 OK
